/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-11-17 15:52:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teamplate.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class leftbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<header class=\"tm-header\" id=\"tm-header\">\n");
      out.write("    <div class=\"tm-header-wrapper\">\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" aria-label=\"Toggle navigation\">\n");
      out.write("            <i class=\"fas fa-bars\"></i>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"tm-site-header\">\n");
      out.write("            <div class=\"mb-3 mx-auto tm-site-logo\"><i class=\"fas fa-times fa-2x\"></i></div>\n");
      out.write("            <h1 class=\"text-center\">Xtra Blog</h1>\n");
      out.write("        </div>\n");
      out.write("        <nav class=\"tm-nav\" id=\"tm-nav\">\n");
      out.write("            <ul>\n");
      out.write("                <li class=\"tm-nav-item active\"><a href=\"index.jsp\" class=\"tm-nav-link\">\n");
      out.write("                    <i class=\"fas fa-home\"></i>\n");
      out.write("                    Blog Home\n");
      out.write("                </a></li>\n");
      out.write("                <li class=\"tm-nav-item\"><a href=\"post.jsp\" class=\"tm-nav-link\">\n");
      out.write("                    <i class=\"fas fa-pen\"></i>\n");
      out.write("                    Single Post\n");
      out.write("                </a></li>\n");
      out.write("                <li class=\"tm-nav-item\"><a href=\"about.jsp\" class=\"tm-nav-link\">\n");
      out.write("                    <i class=\"fas fa-users\"></i>\n");
      out.write("                    About Xtra\n");
      out.write("                </a></li>\n");
      out.write("                <li class=\"tm-nav-item\"><a href=\"contact.jsp\" class=\"tm-nav-link\">\n");
      out.write("                    <i class=\"far fa-comments\"></i>\n");
      out.write("                    Contact Us\n");
      out.write("                </a></li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("        <div class=\"tm-mb-65\">\n");
      out.write("            <a rel=\"nofollow\" href=\"https://fb.com/templatemo\" class=\"tm-social-link\">\n");
      out.write("                <i class=\"fab fa-facebook tm-social-icon\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"https://twitter.com\" class=\"tm-social-link\">\n");
      out.write("                <i class=\"fab fa-twitter tm-social-icon\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"https://instagram.com\" class=\"tm-social-link\">\n");
      out.write("                <i class=\"fab fa-instagram tm-social-icon\"></i>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"https://linkedin.com\" class=\"tm-social-link\">\n");
      out.write("                <i class=\"fab fa-linkedin tm-social-icon\"></i>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"tm-mb-80 pr-5 text-white\">\n");
      out.write("            Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
