/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-11-17 15:52:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"row tm-row\">\n");
      out.write("    <article class=\"col-12 col-md-6 tm-post\">\n");
      out.write("        <hr class=\"tm-hr-primary\">\n");
      out.write("        <a href=\"post.jsp\" class=\"effect-lily tm-post-link tm-pt-60\">\n");
      out.write("            <div class=\"tm-post-link-inner\">\n");
      out.write("                <img src=\"img/img-01.jpg\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("            <span class=\"position-absolute tm-new-badge\">New</span>\n");
      out.write("            <h2 class=\"tm-pt-30 tm-color-primary tm-post-title\">Simple and useful HTML layout</h2>\n");
      out.write("        </a>\n");
      out.write("        <p class=\"tm-pt-30\">\n");
      out.write("            There is a clickable image with beautiful hover effect and active title link for each post item.\n");
      out.write("            Left side is a sticky menu bar. Right side is a blog content that will scroll up and down.\n");
      out.write("        </p>\n");
      out.write("        <div class=\"d-flex justify-content-between tm-pt-45\">\n");
      out.write("            <span class=\"tm-color-primary\">Travel . Events</span>\n");
      out.write("            <span class=\"tm-color-primary\">June 24, 2020</span>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-flex justify-content-between\">\n");
      out.write("            <span>36 comments</span>\n");
      out.write("            <span>by Admin Nat</span>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("    <article class=\"col-12 col-md-6 tm-post\">\n");
      out.write("        <hr class=\"tm-hr-primary\">\n");
      out.write("        <a href=\"post.jsp\" class=\"effect-lily tm-post-link tm-pt-60\">\n");
      out.write("            <div class=\" tm-post-link-inner\">\n");
      out.write("                <img src=\"img/img-02.jpg\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("            <span class=\"position-absolute tm-new-badge\">New</span>\n");
      out.write("            <h2 class=\"tm-pt-30 tm-color-primary tm-post-title\">Multi-purpose blog template</h2>\n");
      out.write("        </a>\n");
      out.write("        <p class=\"tm-pt-30\">\n");
      out.write("            <a rel=\"nofollow\" href=\"https://templatemo.com/tm-553-xtra-blog\" target=\"_blank\">Xtra Blog</a>  is a multi-purpose HTML CSS template from TemplateMo website.\n");
      out.write("            Blog list, single post, about, contact pages are included. Left sidebar fixed width and content area is a fluid full-width.\n");
      out.write("        </p>\n");
      out.write("        <div class=\"d-flex justify-content-between tm-pt-45\">\n");
      out.write("            <span class=\"tm-color-primary\">Creative . Design . Business</span>\n");
      out.write("            <span class=\"tm-color-primary\">June 16, 2020</span>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-flex justify-content-between\">\n");
      out.write("            <span>48 comments</span>\n");
      out.write("            <span>by Admin Sam</span>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("    <article class=\"col-12 col-md-6 tm-post\">\n");
      out.write("        <hr class=\"tm-hr-primary\">\n");
      out.write("        <a href=\"post.jsp\" class=\"effect-lily tm-post-link tm-pt-20\">\n");
      out.write("            <div class=\"tm-post-link-inner\">\n");
      out.write("                <img src=\"img/img-03.jpg\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("            <h2 class=\"tm-pt-30 tm-color-primary tm-post-title\">How can you apply Xtra Blog</h2>\n");
      out.write("        </a>\n");
      out.write("        <p class=\"tm-pt-30\">\n");
      out.write("            You are <u>allowed</u> to convert this template as any kind of CMS theme or template for your custom website builder.\n");
      out.write("            You can also use this for your clients. Thank you for choosing us.\n");
      out.write("        </p>\n");
      out.write("        <div class=\"d-flex justify-content-between tm-pt-45\">\n");
      out.write("            <span class=\"tm-color-primary\">Music . Audio</span>\n");
      out.write("            <span class=\"tm-color-primary\">June 11, 2020</span>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-flex justify-content-between\">\n");
      out.write("            <span>24 comments</span>\n");
      out.write("            <span>by John Walker</span>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("    <article class=\"col-12 col-md-6 tm-post\">\n");
      out.write("        <hr class=\"tm-hr-primary\">\n");
      out.write("        <a href=\"post.jsp\" class=\"effect-lily tm-post-link tm-pt-20\">\n");
      out.write("            <div class=\"tm-post-link-inner\">\n");
      out.write("                <img src=\"img/img-04.jpg\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("            <h2 class=\"tm-pt-30 tm-color-primary tm-post-title\">A little restriction to apply</h2>\n");
      out.write("        </a>\n");
      out.write("        <p class=\"tm-pt-30\">\n");
      out.write("            You are <u>not allowed</u> to re-distribute this template as a downloadable ZIP file on any template collection\n");
      out.write("            website. This is strongly prohibited as we worked hard for this template. Please contact TemplateMo for more information.\n");
      out.write("            <br>For example, <a href=\"https://www.free-css.com/free-css-templates/page272/xtra-blog\" target=\"_blank\">Free-CSS</a> redistributed this Xtra Blog template on their website without asking any permission. It is an illegal act by Free-CSS website doing an unauthorized reposting.</p>\n");
      out.write("        <div class=\"d-flex justify-content-between tm-pt-45\">\n");
      out.write("            <span class=\"tm-color-primary\">Artworks . Design</span>\n");
      out.write("            <span class=\"tm-color-primary\">June 4, 2020</span>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-flex justify-content-between\">\n");
      out.write("            <span>72 comments</span>\n");
      out.write("            <span>by Admin Sam</span>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("    <article class=\"col-12 col-md-6 tm-post\">\n");
      out.write("        <hr class=\"tm-hr-primary\">\n");
      out.write("        <a href=\"post.jsp\" class=\"effect-lily tm-post-link tm-pt-20\">\n");
      out.write("            <div class=\"tm-post-link-inner\">\n");
      out.write("                <img src=\"img/img-05.jpg\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("            <h2 class=\"tm-pt-30 tm-color-primary tm-post-title\">Color hexa values of Xtra Blog</h2>\n");
      out.write("        </a>\n");
      out.write("        <p class=\"tm-pt-30\">\n");
      out.write("            If you wish to kindly support us, please contact us or contribute a small PayPal amount to info [at] templatemo.com that is helpful for us.\n");
      out.write("            <br>\n");
      out.write("            Title #099 New #0CC <br>\n");
      out.write("            <span class=\"tm-color-primary\">Text #999 Line #CCC Next #0CC Prev #F0F0F0</span>\n");
      out.write("        </p>\n");
      out.write("        <div class=\"d-flex justify-content-between tm-pt-45\">\n");
      out.write("            <span class=\"tm-color-primary\">Creative . Video . Audio</span>\n");
      out.write("            <span class=\"tm-color-primary\">May 31, 2020</span>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-flex justify-content-between\">\n");
      out.write("            <span>84 comments</span>\n");
      out.write("            <span>by Admin Sam</span>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("    <article class=\"col-12 col-md-6 tm-post\">\n");
      out.write("        <hr class=\"tm-hr-primary\">\n");
      out.write("        <a href=\"post.jsp\" class=\"effect-lily tm-post-link tm-pt-20\">\n");
      out.write("            <div class=\"tm-post-link-inner\">\n");
      out.write("                <img src=\"img/img-06.jpg\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("            <h2 class=\"tm-pt-30 tm-color-primary tm-post-title\">Donec convallis varius risus</h2>\n");
      out.write("        </a>\n");
      out.write("        <p class=\"tm-pt-30\">\n");
      out.write("            Quisque id ipsum vel sem maximus vulputate sed quis velit. Nunc vel turpis eget orci elementum cursus vitae in eros. Quisque vulputate nulla ut dolor consectetur luctus.\n");
      out.write("        </p>\n");
      out.write("        <div class=\"d-flex justify-content-between tm-pt-45\">\n");
      out.write("            <span class=\"tm-color-primary\">Visual . Artworks</span>\n");
      out.write("            <span class=\"tm-color-primary\">June 16, 2020</span>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"d-flex justify-content-between\">\n");
      out.write("            <span>96 comments</span>\n");
      out.write("            <span>by Admin Sam</span>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("</div>\n");
      out.write("<div class=\"row tm-row tm-mt-100 tm-mb-75\">\n");
      out.write("    <div class=\"tm-prev-next-wrapper\">\n");
      out.write("        <a href=\"#\" class=\"mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20\">Prev</a>\n");
      out.write("        <a href=\"#\" class=\"mb-2 tm-btn tm-btn-primary tm-prev-next\">Next</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"tm-paging-wrapper\">\n");
      out.write("        <span class=\"d-inline-block mr-3\">Page</span>\n");
      out.write("        <nav class=\"tm-paging-nav d-inline-block\">\n");
      out.write("            <ul>\n");
      out.write("                <li class=\"tm-paging-item active\">\n");
      out.write("                    <a href=\"#\" class=\"mb-2 tm-btn tm-paging-link\">1</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"tm-paging-item\">\n");
      out.write("                    <a href=\"#\" class=\"mb-2 tm-btn tm-paging-link\">2</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"tm-paging-item\">\n");
      out.write("                    <a href=\"#\" class=\"mb-2 tm-btn tm-paging-link\">3</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"tm-paging-item\">\n");
      out.write("                    <a href=\"#\" class=\"mb-2 tm-btn tm-paging-link\">4</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
